### ISSUE TITLE
cgmlstfinder results

### ISSUE THREAD

**Issue by sekhwal** [kcri-tz/cgmlstfinder#1]
I finished running cgmlstfinder, ti generated all essential output files including .aln, .frag.gz, .fsa and .res. However, it contains only one sample in results.txt (matrix) and summary.txt files. Is there any way to re-run cgmlstfinder to generate only these files or di I have to start the pipeline from starting.

**Comment by zwets** [comment]
The tool runs single samples at a time, so you need to rerun it for the next sample. Every sample will produce a fresh set of outputs, so make sure you use different output directories.
