### ISSUE TITLE
how to build a custom schema database?

### ISSUE THREAD

**Issue by hevyfly** [kcri-tz/cgmlstfinder#2]
how to build a custom schema from other  existed schema  which are in PubMlst or cgMLST.org?  thank you!

**Comment by zwets** [comment]
This repository is a fork of the upstream reposity at https://bitbucket.org/genomicepidemiology/cgmlstfinder.

The same issue was raised there. You may find helpful information [here](https://bitbucket.org/genomicepidemiology/cgmlstfinder/issues/8/script-to-generate-cgmlstfinder-database).
